name: flutterbase
description: flutterbase
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
#--------------------- Networks & Firebase -----------------------
  dio: ^5.7.0
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^19.5.0
  pretty_dio_logger: ^1.4.0
  pretty_logger: ^1.0.0
  firebase_remote_config: ^6.1.2

#--------------------- Localization & Internationalization -----------------------
  intl: 0.20.2
  easy_localization: 3.0.7+1
  easy_logger: ^0.0.2
#--------------------- Tools -----------------------
  image_picker: ^1.1.2
  file_picker: ^10.3.1
  image_cropper: ^9.1.0
  video_player: ^2.9.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  dotted_border: ^3.1.0
  dropdown_search: ^6.0.2
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_offline: ^5.0.0
  sliver_tools: ^0.2.12
  photo_view: ^0.15.0
  pinput: ^5.0.0
  gaimon: ^1.4.1
  rxdart: ^0.28.0

#--------------------- State Management & Utilities -----------------------
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  get_it: ^8.0.3
  multiple_result: ^5.1.0
  injectable: ^2.5.1

#--------------------- UI & Animations -----------------------
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.1.0
  lottie: ^3.1.2
  skeletonizer: ^2.1.0+1
  flutter_html: ^3.0.0
  flutter_animate: ^4.5.2
#--------------------- Storage & Data -----------------------
  shared_preferences: ^2.2.3
  path: 1.9.1
  path_provider: ^2.1.3

#--------------------- Sharing & Links -----------------------
  share_plus: ^11.1.0
  url_launcher: ^6.3.0
  watcher: ^1.1.2





dev_dependencies:
  build_runner: null 
  easy_localization_loader: null
  flutter_gen_runner: null
  injectable_generator: null
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/svg/base_svg/
    - assets/svg/custom_app_svg/
    - assets/fonts/
    - assets/lottie/ 
    - assets/lottie/data/
    - assets/lottie/error/
    - assets/lottie/loading/
    - assets/lottie/network/
    - assets/lottie/success/
    - assets/translations/


  fonts:
    - family: Expo
      fonts:
      - asset: assets/fonts/ExpoArabicBold.ttf
        weight: 700   
      - asset: assets/fonts/ExpoArabicSemiBold.ttf
        weight: 600
      - asset: assets/fonts/ExpoArabicMedium.ttf
        weight: 500
      - asset: assets/fonts/ExpoArabicBook.ttf
        weight: 400
      - asset: assets/fonts/ExpoArabicLight.ttf
        weight: 300


flutter_gen:
  output: lib/src/config/res/
  line_length: 80
  integrations:
    lottie: true
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      class_name: AppAssets
